"""Add is_vefied field to profile

Revision ID: ccd01232fb35
Revises: 7c50a6d6dec0
Create Date: 2024-04-20 13:21:18.762322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccd01232fb35"
down_revision: Union[str, None] = "7c50a6d6dec0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
    )
    op.alter_column("profiles", "is_verified", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "is_verified")
    # ### end Alembic commands ###
