"""Switch unnullable attrs to nullable in profile model

Revision ID: be1f118b18f6
Revises: 42293f5daab0
Create Date: 2024-04-18 03:08:25.489439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be1f118b18f6"
down_revision: Union[str, None] = "42293f5daab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "hobbies",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column(
        "profiles", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "profiles", "photo_base64", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles", "photo_base64", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles", "status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles",
        "hobbies",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    # ### end Alembic commands ###
