"""empty message

Revision ID: 4572c23c77e3
Revises: fdbad6293ab8
Create Date: 2024-05-25 09:50:04.712236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4572c23c77e3"
down_revision: Union[str, None] = "fdbad6293ab8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profiles", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="unique")
    # ### end Alembic commands ###
