"""empty message

Revision ID: 29f8a7440317
Revises: ccd01232fb35
Create Date: 2024-05-18 23:49:47.266083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f8a7440317'
down_revision: Union[str, None] = 'ccd01232fb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('about', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('vector', postgresql.ARRAY(sa.Float()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'vector')
    op.drop_column('profiles', 'about')
    # ### end Alembic commands ###
